# Generated by Django 2.1.4 on 2019-06-09 23:05

from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    Blog = apps.get_model("blog", "Blog")
    for instance in Blog.objects.all():
        print("Generating slug for %s" % instance)
        instance.save()  # Will trigger slug update


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True, allow_unicode=True, default=None, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
