# Generated by Django 2.1.4 on 2019-06-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
